const CONFIG = {
  introTitle: "Babi à!",
  introDesc: `Hehe này là lần đầu tiên anh gửi mail cho emmm đún hongg,
    Anh muốn hỏi em cái này nèee, em ấn tiếp theo ikk rồi anh nói cho iem bíc nekk`,
  btnIntro: "^^^ nút tiếp theo chỗ này nekk",
  title: "Muốn gửi cho công chúa xinh đẹp đang đọc nì 😙",
  desc: " Bữa anh có ghi tờ note cho em á, chữ anh xấu sợ em hong đọc được, nhưng mà lần này là lần đầu tiên anh viết thư cho ai đó kiểu như zậy nèe, em đọc xong rồi thì trả lời anh cái nèe,  anh hỏng biếc lịch rảnh của em lúc nào hết mà nhắn quài sợ em ngại <3, nên anh làm cái này khi nào em rảnh thì nhắn zô cái này nhắn anh qua đón em , anh đợi emm <3. Ê nhưng có cái em hay đăng bùn bùn, nếu anh là có thể là người lắng nghe nỗi bùn đó được thì anh sẽ giúp em á, anh hỏng có nói xạo em đâuu, vớii em đừng có bùn nữa nhen, gái đẹp thì hong được bùn đou đó <3",
  btnYes: "Vẫn cứ là thích anh <33",
  btnNo: "Không, anh trai à :3",
  question: "Muốn nói gì hong z <3",
  btnReply: "Gửi cho anh <3",
  reply: "Yêu thì yêu mà không yêu thì yêu <33333333",
  mess: "Anh biết mà 🥰",
  messDesc: "Tối nay 6h anh qua đón nhé công chúa.",
  btnAccept: "Okiiiii lun <3 zô nhắn cho anh nèe",
  messLink: "https://www.messenger.com/t/100008278201209",
};
